# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: flight.proto

require 'google/protobuf'


descriptor_data = "\n\x0c\x66light.proto\x12\x06\x66light\"&\n\x11\x46lightByIdRequest\x12\x11\n\tunique_id\x18\x01 \x01(\t\"\xc5\x01\n\x12\x46lightByIdResponse\x12\x11\n\tunique_id\x18\x01 \x01(\t\x12\x13\n\x0b\x66light_date\x18\x02 \x01(\t\x12\x15\n\rflight_number\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\x12#\n\x1bscheduled_departure_airport\x18\x05 \x01(\t\x12!\n\x19scheduled_arrival_airport\x18\x06 \x01(\t\x12\x0b\n\x03std\x18\x07 \x01(\t\x12\x0b\n\x03sta\x18\x08 \x01(\t2T\n\rFlightService\x12\x43\n\nFlightById\x12\x19.flight.FlightByIdRequest\x1a\x1a.flight.FlightByIdResponseb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Flight
  FlightByIdRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("flight.FlightByIdRequest").msgclass
  FlightByIdResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("flight.FlightByIdResponse").msgclass
end
