# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: flight.proto for package 'flight'

require 'grpc'
require 'flight_pb'

module Flight
  module FlightService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'flight.FlightService'

      rpc :FlightById, ::Flight::FlightByIdRequest, ::Flight::FlightByIdResponse
    end

    Stub = Service.rpc_stub_class
  end
end
