# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: navblue.proto for package 'navblue'

require 'grpc'
require 'navblue_pb'

module Navblue
  module NavblueService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'navblue.NavblueService'

      rpc :FlightById, ::Navblue::FlightByIdRequest, ::Navblue::FlightByIdResponse
    end

    Stub = Service.rpc_stub_class
  end
end
