# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: navitaire.proto for package 'navitaire'

require 'grpc'
require 'navitaire_pb'

module Navitaire
  module NavitaireService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'navitaire.NavitaireService'

      rpc :GetStations, ::Google::Protobuf::Empty, ::Navitaire::GetStationsResponse
    end

    Stub = Service.rpc_stub_class
  end
end
