# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: stations.proto for package 'stations'

require 'grpc'
require 'stations_pb'

module Stations
  module StationsService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'stations.StationsService'

      rpc :GetStations, ::Google::Protobuf::Empty, ::Stations::GetStationsResponse
    end

    Stub = Service.rpc_stub_class
  end
end
